### ISSUE TITLE
A roleImplication between two RoleTypes in a Compartment cannot be transformed

### ISSUE THREAD

**Issue by leondart** [leondart/FRaMED#75]
Enviroment:
Windows 7 64bit
Reproduce steps:
1. create a CompartmentType
2. step into the compartment
3. create two RoleTypes
4. draw/create a role implication between the two role types
5. click on save button  or use save short cut
Error Message:
Internal error: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0[Native Method]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance[NativeConstructorAccessorImpl.java:57]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance[DelegatingConstructorAccessorImpl.java:45]
	at java.lang.reflect.Constructor.newInstance[Constructor.java:526]
	at org.eclipse.epsilon.eol.types.EolClasspathNativeTypeDelegate.createInstance[EolClasspathNativeTypeDelegate.java:55]
	at org.eclipse.epsilon.eol.types.AbstractToolNativeTypeDelegate.createInstance[AbstractToolNativeTypeDelegate.java:27]
	at org.eclipse.epsilon.eol.types.EolNativeType.createInstance[EolNativeType.java:48]
	at org.eclipse.epsilon.eol.execute.TypeInitialiserExecutor.initialiseType[TypeInitialiserExecutor.java:30]
	at org.eclipse.epsilon.eol.execute.NewExecutor.execute[NewExecutor.java:29]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.AssignExecutor.execute[AssignExecutor.java:48]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute[StatementBlockExecutor.java:26]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.IfStatementExecutor.execute[IfStatementExecutor.java:43]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.IfStatementExecutor.execute[IfStatementExecutor.java:46]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.IfStatementExecutor.execute[IfStatementExecutor.java:46]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute[StatementBlockExecutor.java:26]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.IfStatementExecutor.execute[IfStatementExecutor.java:43]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute[StatementBlockExecutor.java:26]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.IfStatementExecutor.execute[IfStatementExecutor.java:43]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute[StatementBlockExecutor.java:26]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.ForStatementExecutor.execute[ForStatementExecutor.java:111]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute[StatementBlockExecutor.java:26]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.IfStatementExecutor.execute[IfStatementExecutor.java:43]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute[StatementBlockExecutor.java:26]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.etl.TransformRule.executeSuperRulesAndBody[TransformRule.java:279]
	at org.eclipse.epsilon.etl.TransformRule.transform[TransformRule.java:215]
	at org.eclipse.epsilon.etl.strategy.FastTransformationStrategy.executeTransformations[FastTransformationStrategy.java:165]
	at org.eclipse.epsilon.etl.strategy.FastTransformationStrategy.transformModels[FastTransformationStrategy.java:157]
	at org.eclipse.epsilon.etl.EtlModule.execute[EtlModule.java:127]
	at org.framed.orm.transformation.EpsilonStandalone.execute[EpsilonStandalone.java:59]
	at org.framed.orm.transformation.EpsilonStandalone.execute[EpsilonStandalone.java:51]
	at org.framed.orm.ui.editor.ORMGraphicalEditor.transformModel[ORMGraphicalEditor.java:370]
	at org.framed.orm.ui.editor.ORMGraphicalEditor.doSave[ORMGraphicalEditor.java:335]
	at org.framed.orm.ui.editor.ORMMultiPageEditor.doSave[ORMMultiPageEditor.java:218]
	at org.eclipse.ui.internal.SaveableHelper$2.run[SaveableHelper.java:154]
	at org.eclipse.ui.internal.SaveableHelper$5.run[SaveableHelper.java:283]
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread[ModalContext.java:466]
	at org.eclipse.jface.operation.ModalContext.run[ModalContext.java:374]
	at org.eclipse.ui.internal.WorkbenchWindow$13.run[WorkbenchWindow.java:2157]
	at org.eclipse.swt.custom.BusyIndicator.showWhile[BusyIndicator.java:70]
	at org.eclipse.ui.internal.WorkbenchWindow.run[WorkbenchWindow.java:2153]
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation[SaveableHelper.java:291]
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation[SaveableHelper.java:269]
	at org.eclipse.ui.internal.SaveableHelper.savePart[SaveableHelper.java:159]
	at org.eclipse.ui.internal.WorkbenchPage.saveSaveable[WorkbenchPage.java:3915]
	at org.eclipse.ui.internal.WorkbenchPage.saveEditor[WorkbenchPage.java:3929]
	at org.eclipse.ui.internal.handlers.SaveHandler.execute[SaveHandler.java:54]
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute[HandlerProxy.java:294]
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute[E4HandlerProxy.java:90]
	at sun.reflect.NativeMethodAccessorImpl.invoke0[Native Method]
	at sun.reflect.NativeMethodAccessorImpl.invoke[NativeMethodAccessorImpl.java:57]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke[DelegatingMethodAccessorImpl.java:43]
	at java.lang.reflect.Method.invoke[Method.java:606]
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute[MethodRequestor.java:55]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass[InjectorImpl.java:247]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke[InjectorImpl.java:229]
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke[ContextInjectionFactory.java:132]
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute[HandlerServiceHandler.java:149]
	at org.eclipse.core.commands.Command.executeWithChecks[Command.java:499]
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks[ParameterizedCommand.java:508]
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler[HandlerServiceImpl.java:210]
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand[LegacyHandlerService.java:343]
	at org.eclipse.ui.internal.actions.CommandAction.runWithEvent[CommandAction.java:159]
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection[ActionContributionItem.java:595]
	at org.eclipse.jface.action.ActionContributionItem.access$2[ActionContributionItem.java:511]
	at org.eclipse.jface.action.ActionContributionItem$6.handleEvent[ActionContributionItem.java:462]
	at org.eclipse.swt.widgets.EventTable.sendEvent[EventTable.java:84]
	at org.eclipse.swt.widgets.Display.sendEvent[Display.java:4353]
	at org.eclipse.swt.widgets.Widget.sendEvent[Widget.java:1061]
	at org.eclipse.swt.widgets.Display.runDeferredEvents[Display.java:4172]
	at org.eclipse.swt.widgets.Display.readAndDispatch[Display.java:3761]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run[PartRenderingEngine.java:1151]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault[Realm.java:332]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run[PartRenderingEngine.java:1032]
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI[E4Workbench.java:148]
	at org.eclipse.ui.internal.Workbench$5.run[Workbench.java:636]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault[Realm.java:332]
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench[Workbench.java:579]
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench[PlatformUI.java:150]
	at org.eclipse.ui.internal.ide.application.IDEApplication.start[IDEApplication.java:135]
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run[EclipseAppHandle.java:196]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication[EclipseAppLauncher.java:134]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start[EclipseAppLauncher.java:104]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run[EclipseStarter.java:380]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run[EclipseStarter.java:235]
	at sun.reflect.NativeMethodAccessorImpl.invoke0[Native Method]
	at sun.reflect.NativeMethodAccessorImpl.invoke[NativeMethodAccessorImpl.java:57]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke[DelegatingMethodAccessorImpl.java:43]
	at java.lang.reflect.Method.invoke[Method.java:606]
	at org.eclipse.equinox.launcher.Main.invokeFramework[Main.java:648]
	at org.eclipse.equinox.launcher.Main.basicRun[Main.java:603]
	at org.eclipse.equinox.launcher.Main.run[Main.java:1465]
	at org.eclipse.equinox.launcher.Main.main[Main.java:1438]
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString[NumberFormatException.java:65]
	at java.lang.Integer.parseInt[Integer.java:504]
	at java.lang.Integer.<init>[Integer.java:677]
	... 120 more

	at (bundleentry://2284.fwk27315788/epsilon/CompartmentType.etl@44:19-44:56)
	at (bundleentry://2284.fwk27315788/epsilon/CompartmentType.etl@44:6-44:57)
	at (bundleentry://2284.fwk27315788/epsilon/CompartmentType.etl@43:7-46:6)
	at (bundleentry://2284.fwk27315788/epsilon/CompartmentType.etl@40:7-46:6)
	at (bundleentry://2284.fwk27315788/epsilon/CompartmentType.etl@36:5-46:6)
	at (bundleentry://2284.fwk27315788/epsilon/CompartmentType.etl@34:4-47:5)
	at (bundleentry://2284.fwk27315788/epsilon/CompartmentType.etl@26:3-56:4)
	at (bundleentry://2284.fwk27315788/epsilon/CompartmentType.etl@23:2-57:3)
	at (bundleentry://2284.fwk27315788/epsilon/CompartmentType.etl@22:1-58:2)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.eclipse.epsilon.eol.types.EolClasspathNativeTypeDelegate.createInstance(EolClasspathNativeTypeDelegate.java:55)
	at org.eclipse.epsilon.eol.types.AbstractToolNativeTypeDelegate.createInstance(AbstractToolNativeTypeDelegate.java:27)
	at org.eclipse.epsilon.eol.types.EolNativeType.createInstance(EolNativeType.java:48)
	at org.eclipse.epsilon.eol.execute.TypeInitialiserExecutor.initialiseType(TypeInitialiserExecutor.java:30)
	at org.eclipse.epsilon.eol.execute.NewExecutor.execute(NewExecutor.java:29)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.AssignExecutor.execute(AssignExecutor.java:48)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute(StatementBlockExecutor.java:26)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.IfStatementExecutor.execute(IfStatementExecutor.java:43)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.IfStatementExecutor.execute(IfStatementExecutor.java:46)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.IfStatementExecutor.execute(IfStatementExecutor.java:46)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute(StatementBlockExecutor.java:26)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.IfStatementExecutor.execute(IfStatementExecutor.java:43)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute(StatementBlockExecutor.java:26)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.IfStatementExecutor.execute(IfStatementExecutor.java:43)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute(StatementBlockExecutor.java:26)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.ForStatementExecutor.execute(ForStatementExecutor.java:111)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute(StatementBlockExecutor.java:26)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.IfStatementExecutor.execute(IfStatementExecutor.java:43)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute(StatementBlockExecutor.java:26)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.etl.TransformRule.executeSuperRulesAndBody(TransformRule.java:279)
	at org.eclipse.epsilon.etl.TransformRule.transform(TransformRule.java:215)
	at org.eclipse.epsilon.etl.strategy.FastTransformationStrategy.executeTransformations(FastTransformationStrategy.java:165)
	at org.eclipse.epsilon.etl.strategy.FastTransformationStrategy.transformModels(FastTransformationStrategy.java:157)
	at org.eclipse.epsilon.etl.EtlModule.execute(EtlModule.java:127)
	at org.framed.orm.transformation.EpsilonStandalone.execute(EpsilonStandalone.java:59)
	at org.framed.orm.transformation.EpsilonStandalone.execute(EpsilonStandalone.java:51)
	at org.framed.orm.ui.editor.ORMGraphicalEditor.transformModel(ORMGraphicalEditor.java:370)
	at org.framed.orm.ui.editor.ORMGraphicalEditor.doSave(ORMGraphicalEditor.java:335)
	at org.framed.orm.ui.editor.ORMMultiPageEditor.doSave(ORMMultiPageEditor.java:218)
	at org.eclipse.ui.internal.SaveableHelper$2.run(SaveableHelper.java:154)
	at org.eclipse.ui.internal.SaveableHelper$5.run(SaveableHelper.java:283)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:466)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:374)
	at org.eclipse.ui.internal.WorkbenchWindow$13.run(WorkbenchWindow.java:2157)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2153)
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:291)
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:269)
	at org.eclipse.ui.internal.SaveableHelper.savePart(SaveableHelper.java:159)
	at org.eclipse.ui.internal.WorkbenchPage.saveSaveable(WorkbenchPage.java:3915)
	at org.eclipse.ui.internal.WorkbenchPage.saveEditor(WorkbenchPage.java:3929)
	at org.eclipse.ui.internal.handlers.SaveHandler.execute(SaveHandler.java:54)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:247)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:229)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:149)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:343)
	at org.eclipse.ui.internal.actions.CommandAction.runWithEvent(CommandAction.java:159)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$6.handleEvent(ActionContributionItem.java:462)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: java.lang.reflect.InvocationTargetException
	... 120 more
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:504)
	at java.lang.Integer.<init>(Integer.java:677)
	... 120 more

**Comment by jtandler** [comment]
How can I tag this as fixed!? :/

**Comment by skaldarnar** [comment]
You can just close the issue. :wink: 

Otherwise, you can include a `fixes #75` phrase in your commit message.

**Comment by jtandler** [comment]
Ah now i found that button :D
I misinterpret the "Close and comment" button. Sounded like closes this webpage and saves the comment ;) 
Commit messages are not working because we don't develop on 'master' (i think so)...
