### ISSUE TITLE
Can't save 

### ISSUE THREAD

**Issue by mheider** [leondart/FRaMED#76]
Can't save under MacOSX

Details:
- OS: Mac OS X Yosemite (Version 10.10.3)
- Eclipse:
  Eclipse Platform

  Version: Luna SR2 (4.4.2)
  Build id: M20150204-1700

Exception:
```
Caused by: java.lang.ClassCastException: crom_l1_composed.impl.RoleTypeImpl cannot be cast to crom_l1_composed.RigidType
	... 138 more
Internal error: java.lang.ClassCastException: crom_l1_composed.impl.RoleTypeImpl cannot be cast to crom_l1_composed.RigidType
	at crom_l1_composed.impl.TypedElementImpl.eSet[TypedElementImpl.java:169]
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eSet[BasicEObjectImpl.java:1071]
	at org.eclipse.epsilon.emc.emf.EmfPropertySetter.invoke[EmfPropertySetter.java:68]
	at org.eclipse.epsilon.eol.execute.AssignExecutor.execute[AssignExecutor.java:55]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute[StatementBlockExecutor.java:26]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.IfStatementExecutor.execute[IfStatementExecutor.java:43]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute[StatementBlockExecutor.java:26]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.ForStatementExecutor.execute[ForStatementExecutor.java:111]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute[StatementBlockExecutor.java:26]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.IfStatementExecutor.execute[IfStatementExecutor.java:43]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute[StatementBlockExecutor.java:26]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.ForStatementExecutor.execute[ForStatementExecutor.java:111]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute[StatementBlockExecutor.java:26]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.EolOperation.executeBody[EolOperation.java:276]
	at org.eclipse.epsilon.eol.EolOperation.execute[EolOperation.java:248]
	at org.eclipse.epsilon.eol.EolOperation.execute[EolOperation.java:206]
	at org.eclipse.epsilon.eol.EolOperations.execute[EolOperations.java:119]
	at org.eclipse.epsilon.eol.execute.PointExecutor.executeOperation[PointExecutor.java:145]
	at org.eclipse.epsilon.eol.execute.PointExecutor.execute[PointExecutor.java:86]
	at org.eclipse.epsilon.eol.execute.PointExecutor.execute[PointExecutor.java:48]
	at org.eclipse.epsilon.eol.execute.PointExecutor.execute[PointExecutor.java:93]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute[StatementBlockExecutor.java:26]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.ForStatementExecutor.execute[ForStatementExecutor.java:111]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:175]
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute[StatementBlockExecutor.java:26]
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST[ExecutorFactory.java:205]
	at org.eclipse.epsilon.erl.ErlModule.execute[ErlModule.java:88]
	at org.eclipse.epsilon.etl.EtlModule.execute[EtlModule.java:130]
	at org.framed.orm.transformation.EpsilonStandalone.execute[EpsilonStandalone.java:59]
	at org.framed.orm.transformation.EpsilonStandalone.execute[EpsilonStandalone.java:51]
	at org.framed.orm.ui.editor.ORMGraphicalEditor.transformModel[ORMGraphicalEditor.java:370]
	at org.framed.orm.ui.editor.ORMGraphicalEditor.doSave[ORMGraphicalEditor.java:335]
	at org.framed.orm.ui.editor.ORMMultiPageEditor.doSave[ORMMultiPageEditor.java:218]
	at org.eclipse.ui.internal.SaveableHelper$2.run[SaveableHelper.java:154]
	at org.eclipse.ui.internal.SaveableHelper$5.run[SaveableHelper.java:283]
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread[ModalContext.java:466]
	at org.eclipse.jface.operation.ModalContext.run[ModalContext.java:374]
	at org.eclipse.ui.internal.WorkbenchWindow$13.run[WorkbenchWindow.java:2157]
	at org.eclipse.swt.custom.BusyIndicator.showWhile[BusyIndicator.java:70]
	at org.eclipse.ui.internal.WorkbenchWindow.run[WorkbenchWindow.java:2153]
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation[SaveableHelper.java:291]
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation[SaveableHelper.java:269]
	at org.eclipse.ui.internal.SaveableHelper.savePart[SaveableHelper.java:159]
	at org.eclipse.ui.internal.WorkbenchPage.saveSaveable[WorkbenchPage.java:3915]
	at org.eclipse.ui.internal.WorkbenchPage.saveEditor[WorkbenchPage.java:3929]
	at org.eclipse.ui.internal.handlers.SaveHandler.execute[SaveHandler.java:54]
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute[HandlerProxy.java:294]
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute[E4HandlerProxy.java:90]
	at sun.reflect.NativeMethodAccessorImpl.invoke0[Native Method]
	at sun.reflect.NativeMethodAccessorImpl.invoke[NativeMethodAccessorImpl.java:62]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke[DelegatingMethodAccessorImpl.java:43]
	at java.lang.reflect.Method.invoke[Method.java:497]
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute[MethodRequestor.java:55]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass[InjectorImpl.java:247]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke[InjectorImpl.java:229]
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke[ContextInjectionFactory.java:132]
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute[HandlerServiceHandler.java:149]
	at org.eclipse.core.commands.Command.executeWithChecks[Command.java:499]
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks[ParameterizedCommand.java:508]
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler[HandlerServiceImpl.java:210]
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand[KeyBindingDispatcher.java:286]
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press[KeyBindingDispatcher.java:507]
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent[KeyBindingDispatcher.java:558]
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings[KeyBindingDispatcher.java:378]
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0[KeyBindingDispatcher.java:324]
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent[KeyBindingDispatcher.java:86]
	at org.eclipse.swt.widgets.EventTable.sendEvent[EventTable.java:84]
	at org.eclipse.swt.widgets.Display.filterEvent[Display.java:1098]
	at org.eclipse.swt.widgets.Display.sendEvent[Display.java:4195]
	at org.eclipse.swt.widgets.Widget.sendEvent[Widget.java:1467]
	at org.eclipse.swt.widgets.Widget.sendEvent[Widget.java:1490]
	at org.eclipse.swt.widgets.Widget.sendEvent[Widget.java:1475]
	at org.eclipse.swt.widgets.Widget.sendKeyEvent[Widget.java:1504]
	at org.eclipse.swt.widgets.Widget.sendKeyEvent[Widget.java:1500]
	at org.eclipse.swt.widgets.Canvas.sendKeyEvent[Canvas.java:496]
	at org.eclipse.swt.widgets.Control.doCommandBySelector[Control.java:1060]
	at org.eclipse.swt.widgets.Display.windowProc[Display.java:5730]
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend[Native Method]
	at org.eclipse.swt.internal.cocoa.NSResponder.interpretKeyEvents[NSResponder.java:68]
	at org.eclipse.swt.widgets.Composite.keyDown[Composite.java:594]
	at org.eclipse.swt.widgets.Display.windowProc[Display.java:5640]
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper[Native Method]
	at org.eclipse.swt.widgets.Widget.callSuper[Widget.java:221]
	at org.eclipse.swt.widgets.Widget.windowSendEvent[Widget.java:2105]
	at org.eclipse.swt.widgets.Shell.windowSendEvent[Shell.java:2329]
	at org.eclipse.swt.widgets.Display.windowProc[Display.java:5702]
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper[Native Method]
	at org.eclipse.swt.widgets.Display.applicationSendEvent[Display.java:5139]
	at org.eclipse.swt.widgets.Display.applicationProc[Display.java:5288]
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend[Native Method]
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent[NSApplication.java:128]
	at org.eclipse.swt.widgets.Display.readAndDispatch[Display.java:3666]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run[PartRenderingEngine.java:1151]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault[Realm.java:332]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run[PartRenderingEngine.java:1032]
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI[E4Workbench.java:148]
	at org.eclipse.ui.internal.Workbench$5.run[Workbench.java:636]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault[Realm.java:332]
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench[Workbench.java:579]
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench[PlatformUI.java:150]
	at org.eclipse.ui.internal.ide.application.IDEApplication.start[IDEApplication.java:135]
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run[EclipseAppHandle.java:196]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication[EclipseAppLauncher.java:134]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start[EclipseAppLauncher.java:104]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run[EclipseStarter.java:380]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run[EclipseStarter.java:235]
	at sun.reflect.NativeMethodAccessorImpl.invoke0[Native Method]
	at sun.reflect.NativeMethodAccessorImpl.invoke[NativeMethodAccessorImpl.java:62]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke[DelegatingMethodAccessorImpl.java:43]
	at java.lang.reflect.Method.invoke[Method.java:497]
	at org.eclipse.equinox.launcher.Main.invokeFramework[Main.java:648]
	at org.eclipse.equinox.launcher.Main.basicRun[Main.java:603]
	at org.eclipse.equinox.launcher.Main.run[Main.java:1465]
	at org.eclipse.equinox.launcher.Main.main[Main.java:1438]

	at (bundleentry://853.fwk49619396/epsilon/Type.etl@89:5-89:25)
	at (bundleentry://853.fwk49619396/epsilon/Type.etl@88:4-90:5)
	at (bundleentry://853.fwk49619396/epsilon/Type.etl@79:3-92:4)
	at (bundleentry://853.fwk49619396/epsilon/Type.etl@78:2-93:3)
	at (bundleentry://853.fwk49619396/epsilon/Type.etl@51:1-96:2)
	at (bundleentry://853.fwk49619396/epsilon/RoleType.etl@36:2-36:21)
	at (bundleentry://853.fwk49619396/epsilon/RoleType.etl@28:1-37:2)
	at (bundleentry://853.fwk49619396/epsilon/CompartmentType.etl@27:20-27:29)
	at (bundleentry://853.fwk49619396/epsilon/CompartmentType.etl@27:3-27:31)
	at (bundleentry://853.fwk49619396/epsilon/CompartmentType.etl@24:2-56:3)
	at (bundleentry://853.fwk49619396/epsilon/CompartmentType.etl@23:1-57:2)

	at crom_l1_composed.impl.TypedElementImpl.eSet(TypedElementImpl.java:169)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eSet(BasicEObjectImpl.java:1071)
	at org.eclipse.epsilon.emc.emf.EmfPropertySetter.invoke(EmfPropertySetter.java:68)
	at org.eclipse.epsilon.eol.execute.AssignExecutor.execute(AssignExecutor.java:55)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute(StatementBlockExecutor.java:26)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.IfStatementExecutor.execute(IfStatementExecutor.java:43)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute(StatementBlockExecutor.java:26)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.ForStatementExecutor.execute(ForStatementExecutor.java:111)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute(StatementBlockExecutor.java:26)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.IfStatementExecutor.execute(IfStatementExecutor.java:43)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute(StatementBlockExecutor.java:26)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.ForStatementExecutor.execute(ForStatementExecutor.java:111)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute(StatementBlockExecutor.java:26)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.EolOperation.executeBody(EolOperation.java:276)
	at org.eclipse.epsilon.eol.EolOperation.execute(EolOperation.java:248)
	at org.eclipse.epsilon.eol.EolOperation.execute(EolOperation.java:206)
	at org.eclipse.epsilon.eol.EolOperations.execute(EolOperations.java:119)
	at org.eclipse.epsilon.eol.execute.PointExecutor.executeOperation(PointExecutor.java:145)
	at org.eclipse.epsilon.eol.execute.PointExecutor.execute(PointExecutor.java:86)
	at org.eclipse.epsilon.eol.execute.PointExecutor.execute(PointExecutor.java:48)
	at org.eclipse.epsilon.eol.execute.PointExecutor.execute(PointExecutor.java:93)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute(StatementBlockExecutor.java:26)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.ForStatementExecutor.execute(ForStatementExecutor.java:111)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:175)
	at org.eclipse.epsilon.eol.execute.StatementBlockExecutor.execute(StatementBlockExecutor.java:26)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeAST(ExecutorFactory.java:205)
	at org.eclipse.epsilon.erl.ErlModule.execute(ErlModule.java:88)
	at org.eclipse.epsilon.etl.EtlModule.execute(EtlModule.java:130)
	at org.framed.orm.transformation.EpsilonStandalone.execute(EpsilonStandalone.java:59)
	at org.framed.orm.transformation.EpsilonStandalone.execute(EpsilonStandalone.java:51)
	at org.framed.orm.ui.editor.ORMGraphicalEditor.transformModel(ORMGraphicalEditor.java:370)
	at org.framed.orm.ui.editor.ORMGraphicalEditor.doSave(ORMGraphicalEditor.java:335)
	at org.framed.orm.ui.editor.ORMMultiPageEditor.doSave(ORMMultiPageEditor.java:218)
	at org.eclipse.ui.internal.SaveableHelper$2.run(SaveableHelper.java:154)
	at org.eclipse.ui.internal.SaveableHelper$5.run(SaveableHelper.java:283)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:466)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:374)
	at org.eclipse.ui.internal.WorkbenchWindow$13.run(WorkbenchWindow.java:2157)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2153)
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:291)
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:269)
	at org.eclipse.ui.internal.SaveableHelper.savePart(SaveableHelper.java:159)
	at org.eclipse.ui.internal.WorkbenchPage.saveSaveable(WorkbenchPage.java:3915)
	at org.eclipse.ui.internal.WorkbenchPage.saveEditor(WorkbenchPage.java:3929)
	at org.eclipse.ui.internal.handlers.SaveHandler.execute(SaveHandler.java:54)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:247)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:229)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:149)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:286)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:507)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:558)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:378)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:324)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:86)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1098)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4195)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1467)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1490)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1475)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1504)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1500)
	at org.eclipse.swt.widgets.Canvas.sendKeyEvent(Canvas.java:496)
	at org.eclipse.swt.widgets.Control.doCommandBySelector(Control.java:1060)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5730)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSResponder.interpretKeyEvents(NSResponder.java:68)
	at org.eclipse.swt.widgets.Composite.keyDown(Composite.java:594)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5640)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:221)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2105)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2329)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5702)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5139)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5288)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:128)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3666)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: java.lang.ClassCastException: crom_l1_composed.impl.RoleTypeImpl cannot be cast to crom_l1_composed.RigidType
	... 138 more
```

**Comment by Eden-06** [comment]
Unable to reproduce.
